[prune]
  go-tests = true
  unused-packages = true


[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "gopkg.in/ldap.v2"
  version = "2.5.1"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"
